# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/william/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.5153.40/CLion.app/Contents/bin/cmake/mac/bin/cmake"

# The command to remove a file.
RM = "/Users/william/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.5153.40/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/william/Desktop/BoilerBot/2019/CV Team/ClassifierAccuracy/armor-detection-cascade"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/william/Desktop/BoilerBot/2019/CV Team/ClassifierAccuracy/armor-detection-cascade"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/william/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.5153.40/CLion.app/Contents/bin/cmake/mac/bin/cmake" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/william/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.5153.40/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/william/Desktop/BoilerBot/2019/CV Team/ClassifierAccuracy/armor-detection-cascade/CMakeFiles" "/Users/william/Desktop/BoilerBot/2019/CV Team/ClassifierAccuracy/armor-detection-cascade/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/william/Desktop/BoilerBot/2019/CV Team/ClassifierAccuracy/armor-detection-cascade/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named armor-detection

# Build rule for target.
armor-detection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 armor-detection
.PHONY : armor-detection

# fast build rule for target.
armor-detection/fast:
	$(MAKE) -f CMakeFiles/armor-detection.dir/build.make CMakeFiles/armor-detection.dir/build
.PHONY : armor-detection/fast

Settings.o: Settings.cpp.o

.PHONY : Settings.o

# target to build an object file
Settings.cpp.o:
	$(MAKE) -f CMakeFiles/armor-detection.dir/build.make CMakeFiles/armor-detection.dir/Settings.cpp.o
.PHONY : Settings.cpp.o

Settings.i: Settings.cpp.i

.PHONY : Settings.i

# target to preprocess a source file
Settings.cpp.i:
	$(MAKE) -f CMakeFiles/armor-detection.dir/build.make CMakeFiles/armor-detection.dir/Settings.cpp.i
.PHONY : Settings.cpp.i

Settings.s: Settings.cpp.s

.PHONY : Settings.s

# target to generate assembly for a file
Settings.cpp.s:
	$(MAKE) -f CMakeFiles/armor-detection.dir/build.make CMakeFiles/armor-detection.dir/Settings.cpp.s
.PHONY : Settings.cpp.s

armor-detection.o: armor-detection.cpp.o

.PHONY : armor-detection.o

# target to build an object file
armor-detection.cpp.o:
	$(MAKE) -f CMakeFiles/armor-detection.dir/build.make CMakeFiles/armor-detection.dir/armor-detection.cpp.o
.PHONY : armor-detection.cpp.o

armor-detection.i: armor-detection.cpp.i

.PHONY : armor-detection.i

# target to preprocess a source file
armor-detection.cpp.i:
	$(MAKE) -f CMakeFiles/armor-detection.dir/build.make CMakeFiles/armor-detection.dir/armor-detection.cpp.i
.PHONY : armor-detection.cpp.i

armor-detection.s: armor-detection.cpp.s

.PHONY : armor-detection.s

# target to generate assembly for a file
armor-detection.cpp.s:
	$(MAKE) -f CMakeFiles/armor-detection.dir/build.make CMakeFiles/armor-detection.dir/armor-detection.cpp.s
.PHONY : armor-detection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... armor-detection"
	@echo "... Settings.o"
	@echo "... Settings.i"
	@echo "... Settings.s"
	@echo "... armor-detection.o"
	@echo "... armor-detection.i"
	@echo "... armor-detection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

